# ENVIRONMENT VARIABLES

# As of writing this, cache is not supported in schdeuled workflows
# TODO: fix this when cache is updaed to support schdeuled workflows

name: Cron

on: 
  schedule:
    - cron:  '0 4 * * *'

jobs:
  test-jest:
    name: Test - Jest
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Yarn Install
        run: yarn install --frozen-lockfile
      - name: Test
        run: yarn test --watchAll=false --coverage --ci
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
          AMPLITUDE_KEY: ${{ secrets.AMPLITUDE_KEY }}
          AWS_APPSYNC_URL: ${{ secrets.AWS_APPSYNC_URL }}
          AWS_APPSYNC_REGION: ${{ secrets.AWS_APPSYNC_REGION }}
          AWS_APPSYNC_API_KEY: ${{ secrets.AWS_APPSYNC_API_KEY }}
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_ACCESS_TOKEN: ${{ secrets.CONTENTFUL_ACCESS_TOKEN }}
          CONTENTFUL_ACCESS_TOKEN_DRAFTS: ${{ secrets.CONTENTFUL_ACCESS_TOKEN_DRAFTS }}
      - uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # optional
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }} # required
        if: ${{ failure() }}